.\"-
.\" Copyright (c) 2003-2012 René Ladan. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.

.Dd May 10, 2006
.Dt BIOSFONT 4
.Os
.Sh NAME
.Nm biosfont
.Nd retrieve font bitmaps from BIOS memory
.Sh SYNOPSIS
.Cd /dev/biosfont
.Sh DESCRIPTION
The special file
.Pa /dev/biosfont
is an interface to retrieve font bitmaps from the
.Tn BIOS
memory.
The fonts represented are the native system fonts.
The complete ASCII set (256 characters) can be retrieved.
.Sh IOCTL INTERFACE
The characters can be retrieved using the
.Fn ioctl
call.
The parameters are:
.Bl -tag -width indent
.It Dv BIOSFONT_ASCII
The call identifier for to use for
.Nm biosfont
calls.
.It Dv &ch
A reference to an instance of 
.Fa t_biosfont
which is defined in the header file.
.Fa t_biosfont
has two fields:
.Bl -tag -width indent
.It Fa u_char bitmap[8]
The output, contains the bitmap scanlines.
The top scanline is stored in bitmap[0], the bottom scanline is stored in bitmap[7].
The scanlines themselves are stored little endian (MSB first).
.It Fa u_char nr
ASCII code of character to retrieve, range is bound to 0 <= nr <= 255
.El
.El
.Sh COMPATIBILITY
Due to a braindead endianness implementation the driver is only guaranteed to work on i386 and amd64 architectures.
These are also the only architectures known to the author to actually have the bitmap fonts.
.Sh FILES
.Bl -tag -width indent
.It Pa /usr/local/include/biosfont.h
The header file to include when accessing the driver.
.It Pa /dev/biosfont
The device node for the driver.
.It Pa /boot/modules/biosfont.ko
The kernel module to load when using the driver.
.El
.Sh HISTORY
The
.Nm biosfont
driver was first written in August 2003, and rewritten in April 2006 when the original sources were lost (oops).
It was released to the public on May 7, 2006.
.Pp
Patches can be send to the author
.An Rene Ladan Aq r.c.ladan@gmail.com .
