# Copright (c) Rene Ladan <r.c.ladan@gmail.com>, 2-claused BSD license

SRCS=biosfont.c
KMOD=biosfont
# Fallback value of not set by sysutils/biosfont port :
KMODDIR?=/boot/modules

.include <bsd.kmod.mk>
